name: Build FFmpeg and Node Addon

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    env:
      PREFIX: ${{ github.workspace }}/buildout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential pkg-config yasm nasm libtool git python3

      - name: Clone FFmpeg release/7.1 into ffmpeg_src
        run: |
          rm -rf ffmpeg_src
          git clone --depth 1 --branch release/7.1 https://git.ffmpeg.org/ffmpeg.git ffmpeg_src

      - name: Apply repository patches to ffmpeg_src (if any)
        run: |
          set -euo pipefail
          if compgen -G "patches/*.patch" > /dev/null; then
            echo "Applying patches to ffmpeg_src"
            mkdir -p ffmpeg_src
            cp -v patches/*.patch ffmpeg_src/ || true
            cd ffmpeg_src
            git config user.email "action@users.noreply.github.com"
            git config user.name "GitHub Actions"
            # try git am first
            if git am --3way --committer-date-is-author-date --signoff --keep-cr *.patch; then
              echo "git am succeeded"
            else
              echo "git am failed; showing current patch and trying fallback"
              git am --show-current-patch=diff || true
              git status --porcelain --untracked-files=all || true
              # fallback: try applying patches with dos2unix then git apply
              if command -v dos2unix >/dev/null 2>&1; then
                dos2unix *.patch || true
              else
                sed -i 's/\r$//' *.patch || true
              fi
              # attempt git am again
              if git am --3way --committer-date-is-author-date --signoff --keep-cr *.patch; then
                echo "git am succeeded after normalizing line endings"
              else
                echo "git am still failed; trying git apply --reject --whitespace=fix"
                if git apply --reject --whitespace=fix *.patch; then
                  echo "git apply succeeded"
                  # commit the results
                  git add -A
                  git commit -m "Apply patches (git apply fallback)" || true
                else
                  echo "git apply failed; dumping diagnostic info"
                  git am --abort || true
                  echo "--- failed patch diff ---"
                  git diff --no-prefix || true
                  echo "--- ls -la ---"
                  ls -la
                  exit 1
                fi
              fi
            fi
          else
            echo "No patches found in patches/"
          fi
        shell: bash

      - name: Configure & build static FFmpeg
        run: |
          chmod +x scripts/build_ffmpeg_linux.sh || true
          ./scripts/build_ffmpeg_linux.sh "$PREFIX"

      - name: Show installed libs
        run: ls -la "$PREFIX/lib" || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm deps
        run: npm ci

      - name: Configure Node addon (point to built FFmpeg)
        run: npx cmake-js configure -- -DFFMPEG_SOURCE_DIR="$PREFIX"

      - name: Build Node addon (cmake-js)
        run: npx cmake-js build --arch=x64 --runtime=node

      - name: Upload built addon
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-addon-linux
          path: |
            build/*
            Release/*
            buildout/lib

  build-windows:
    name: Build on Windows (MSVC)
    runs-on: windows-2022
    env:
      PREFIX: ${{ github.workspace }}\buildout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MSYS2 and required packages
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            git
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-yasm
            mingw-w64-x86_64-nasm

      - name: Clone FFmpeg release/7.1 into ffmpeg_src
        run: |
          if (Test-Path ffmpeg_src) { Remove-Item -Recurse -Force ffmpeg_src }
          git clone --depth 1 --branch release/7.1 https://git.ffmpeg.org/ffmpeg.git ffmpeg_src

      - name: Apply repository patches to ffmpeg_src (if any) on Windows
        shell: 'bash --login -eo pipefail {0}'
        run: |
          set -euo pipefail
          shopt -s nullglob || true
          if compgen -G "patches/*.patch" > /dev/null; then
            echo "Applying patches to ffmpeg_src"
            mkdir -p ffmpeg_src
            cp -v patches/*.patch ffmpeg_src/ || true
            cd ffmpeg_src
            git config user.email "action@users.noreply.github.com"
            git config user.name "GitHub Actions"
            if git am --3way --committer-date-is-author-date --signoff --keep-cr *.patch; then
              echo "git am succeeded"
            else
              echo "git am failed; showing current patch and trying fallback"
              git am --show-current-patch=diff || true
              git status --porcelain --untracked-files=all || true
              # Normalize line endings on Windows runner (use sed if dos2unix unavailable)
              if command -v dos2unix >/dev/null 2>&1; then
                dos2unix *.patch || true
              else
                sed -i 's/\r$//' *.patch || true
              fi
              if git am --3way --committer-date-is-author-date --signoff --keep-cr *.patch; then
                echo "git am succeeded after normalizing line endings"
              else
                echo "git am still failed; trying git apply --reject --whitespace=fix"
                if git apply --reject --whitespace=fix *.patch; then
                  echo "git apply succeeded"
                  git add -A
                  git commit -m "Apply patches (git apply fallback)" || true
                else
                  echo "git apply failed; dumping diagnostic info"
                  git am --abort || true
                  git diff --no-prefix || true
                  ls -la || true
                  exit 1
                fi
              fi
            fi
          else
            echo "No patches found in patches/"
          fi

      - name: Build FFmpeg with MSVC via provided script (PowerShell -> MSYS2)
        shell: pwsh
        run: |
            $ErrorActionPreference = 'Stop'

            # Resolve GitHub workspace
            $pwdWin = $env:GITHUB_WORKSPACE
            if (-not $pwdWin) {
            Write-Host "GITHUB_WORKSPACE empty; using current directory"
            $pwdWin = (Get-Location).Path
            }
            Write-Host "PWD_WIN = $pwdWin"

            # Debug listing
            Get-ChildItem -Path $pwdWin -Recurse -Depth 1 | ForEach-Object { $_.FullName }

            # Convert C:\path\to\repo -> /c/path/to/repo for MSYS
            $drive = $pwdWin.Substring(0,1).ToLower()
            $rest = $pwdWin.Substring(2) -replace '\\','/'
            $msysPwd = "/$drive$rest"
            Write-Host "MSYS_PWD = $msysPwd"

            # Ensure script exists
            if (-not (Test-Path (Join-Path $pwdWin 'scripts\build_ffmpeg_win.sh'))) {
            Write-Error "ERROR: scripts/build_ffmpeg_win.sh not found in $pwdWin"
            exit 2
            }

            # Locate Visual Studio via vswhere
            $vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
            if (Test-Path $vswhere) {
            $vsInstall = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
            $vsInstall = $vsInstall.Trim()
            }

            if ($vsInstall -and (Test-Path (Join-Path $vsInstall 'VC\Auxiliary\Build\vcvars64.bat'))) {
            Write-Host "Found VS at $vsInstall"
            } else {
            Write-Warning "vswhere not found or vcvars64.bat missing. Continuing but MSVC environment may be missing."
            }

            # Call MSYS bash with the MSYS path
            $bash = 'C:\msys64\usr\bin\bash.exe'
            if (-not (Test-Path $bash)) {
            Write-Error "ERROR: MSYS2 bash not found at $bash"
            exit 1
            }

            if ($vsInstall) {
            # Use cmd to call vcvars and then call msys bash in that env
            $vcvars = Join-Path $vsInstall 'VC\Auxiliary\Build\vcvars64.bat'
            $cmd = "& `"$vcvars`" && `"$bash`" -lc 'cd \"$msysPwd\" && chmod +x scripts/build_ffmpeg_win.sh && ./scripts/build_ffmpeg_win.sh `"$PREFIX`"'"
            Write-Host "Running: cmd /c $cmd"
            cmd /c $cmd
            } else {
            & $bash -lc "cd '$msysPwd' && chmod +x scripts/build_ffmpeg_win.sh && ./scripts/build_ffmpeg_win.sh '$env:PREFIX'"
            }


      - name: Show installed libs
        run: ls -la "$PREFIX/lib" || true
        shell: 'bash --login -eo pipefail {0}'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm deps
        run: npm ci

      - name: Configure Node addon (point to built FFmpeg)
        shell: 'bash --login -eo pipefail {0}'
        run: npx cmake-js configure -- -DFFMPEG_SOURCE_DIR="$PREFIX"

      - name: Build Node addon (cmake-js) on Windows
        shell: 'bash --login -eo pipefail {0}'
        run: npx cmake-js build --arch=x64 --runtime=node

      - name: Upload built addon
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-addon-windows
          path: |
            build\*
            Release\*
            buildout\lib
  build-macos:
    name: Build on macOS
    runs-on: macos-latest
    env:
      PREFIX: ${{ github.workspace }}/buildout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies (Homebrew)
        run: |
          brew update
          brew install automake autoconf pkg-config yasm nasm libtool git python3

      - name: Clone FFmpeg release/7.1 into ffmpeg_src
        run: |
          rm -rf ffmpeg_src
          git clone --depth 1 --branch release/7.1 https://git.ffmpeg.org/ffmpeg.git ffmpeg_src

      - name: Apply repository patches to ffmpeg_src (if any) on macOS
        run: |
          set -euo pipefail
          if compgen -G "patches/*.patch" > /dev/null; then
            echo "Applying patches to ffmpeg_src"
            mkdir -p ffmpeg_src
            cp -v patches/*.patch ffmpeg_src/ || true
            cd ffmpeg_src
            git config user.email "action@users.noreply.github.com"
            git config user.name "GitHub Actions"
            if git am --3way --committer-date-is-author-date --signoff --keep-cr *.patch; then
              echo "git am succeeded"
            else
              echo "git am failed; showing current patch and trying fallback"
              git am --show-current-patch=diff || true
              git status --porcelain --untracked-files=all || true
              sed -i '' -e $'s/\r$//' *.patch || true
              if git am --3way --committer-date-is-author-date --signoff --keep-cr *.patch; then
                echo "git am succeeded after normalizing line endings"
              else
                echo "git am still failed; trying git apply --reject --whitespace=fix"
                if git apply --reject --whitespace=fix *.patch; then
                  echo "git apply succeeded"
                  git add -A
                  git commit -m "Apply patches (git apply fallback)" || true
                else
                  echo "git apply failed; dumping diagnostic info"
                  git am --abort || true
                  git diff --no-prefix || true
                  ls -la || true
                  exit 1
                fi
              fi
            fi
          else
            echo "No patches found in patches/"
          fi

      - name: Configure & build static FFmpeg
        run: |
          chmod +x scripts/build_ffmpeg_mac.sh || true
          ./scripts/build_ffmpeg_mac.sh "$PREFIX"

      - name: Show installed libs
        run: ls -la "$PREFIX/lib" || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm deps
        run: npm ci

      - name: Configure Node addon (point to built FFmpeg)
        run: npx cmake-js configure -- -DFFMPEG_SOURCE_DIR="$PREFIX"

      - name: Build Node addon (cmake-js)
        run: npx cmake-js build --arch=x64 --runtime=node

      - name: Upload built addon
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-addon-macos
          path: |
            build/*
            Release/*
            buildout/lib
